#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100
for num in $(seq 100)
do
    if [[ $((num %3)) = 0 && $((num %5)) = 0 ]]; then
        echo FizzBuzz
    elif [[ $((num %3)) = 0 ]]; then
        echo Fizz
    elif [[ $((num %5)) = 0 ]]; then
        echo Buzz
    else
        echo "$num"
    fi
done
