#!/usr/bin/env bash
# Change localhost to 127.0.0.2 and alias facebook to 8.8.8.8 using hosts file
cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
